spring.datasource.url=jdbc:mysql://mysql-2869bd0e-mithleshkumar329460-6a1a.g.aivencloud.com:21713/defaultdb?ssl-mode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=${DB}


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true